[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
autorestart=true

[program:gunicorn]
command=/usr/local/bin/gunicorn -c /app/gunicorn_config.py run:app
directory=/app
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
autorestart=true
stopasgroup=true
